### ISSUE TITLE
Comparison to `pod`

### ISSUE THREAD

**Issue by dtolnay** [randomites/plain#1]
This crate looks a lot like the existing [`pod`](https://github.com/arcnmx/nue) ("plain old data") crate. Are there any notable advantages or differences?

**Comment by le-jzr** [comment]
Oh! I didn't know about that one!

But to answer your question, I'd say scope is the major difference. `plain` provides four functions (+method wrappers) and its implementation consists of exactly four lines of unsafe code. `pod`, on the other hand, provides a wide arsenal of various methods I will never need, it is full of various transmutes and unsafe blocks, and it has dependencies.

In other words, `plain` is much, much plainer. :-P

**Comment by dtolnay** [comment]
:+1:
