### ISSUE TITLE
Large argument to slice_from_bytes_len leads to unsafety when overflow checks are disabled

### ISSUE THREAD

**Issue by scurest** [randomites/plain#2]
Consider this program run with integer overflow checks disabled

`````rust
extern crate plain;

// Assume a 64-bit target.
const HUGE: usize = 1 << 63;

fn main() {
    let b = b"";
    let u: &[u32] = plain::slice_from_bytes_len(b, HUGE).unwrap();
    println!("{}", u.len()); // prints HUGE
    println!("{}", u[9999999]); // segfault!
}
`````

which goes through `check_length` to determine if the buffer is long enough

https://github.com/randomites/plain/blob/6b05268e80f1e8e59cf15da689aa5bcc20aae7b4/src/methods.rs#L22-L28

In this case, the multiplication on line 23 overflows giving 0, so the check passes.

The multiplication just needs to be done with something like this instead

````rust
len.checked_mul(mem::size_of::<T>()).ok_or(Error::TooShort)?
````

**Comment by le-jzr** [comment]
Oops. This is embarassing, given that the whole purpose of the crate is to prevent this kind of bugs. Thanks for noticing and reporting this!
Fixed in commit https://github.com/randomites/plain/commit/20087d4e6e45f9cfa2922a88553d3b1e9168da64.
